services:
  - type: web
    name: actorsync
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec puma
    envVars:
      - key: RACK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: TMDB_API_KEY
        value: changeme
      - key: SENTRY_DSN
        value: changeme
      - key: REDIS_URL
        fromService:
          type: redis
          name: actorsync-redis
          property: connectionString
    healthCheckPath: /health/simple
    plan: free
    region: oregon

  - type: redis
    name: actorsync-redis
    plan: free
    region: oregon
    ipAllowList: []